version: 2
executorType: docker
containerInfo:
  - image: ubuntu:14.04
    cmd: ["/bin/bash"]
stages:
  build:
    workDir: ~/kube-distribution
    steps:
      - type: checkout
      - type: shell
        shell: /bin/bash
        command: echo 127.0.0.1 devhost | sudo tee -a /etc/hosts