version: 2
executorType: docker
containerInfo:
  - image: ubuntu:16.04
    cmd: ["/bin/bash"]
stages:
  build:
    workDir: ~/kube-distribution
    steps:
      - type: checkout
      - type: shell
        shell: /bin/bash
        command: echo hello